"""Initial migration

Revision ID: b07fb0335200
Revises: becc9c0631a4
Create Date: 2025-12-07 10:09:30.730864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07fb0335200'
down_revision = 'becc9c0631a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
