"""initial migration

Revision ID: becc9c0631a4
Revises: 
Create Date: 2025-12-07 10:16:13.428949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becc9c0631a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('price_ngn', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_sponsored', sa.Boolean(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('learning_outcomes', sa.JSON(), nullable=True),
    sa.Column('syllabus', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_code'), 'programs', ['code'], unique=True)
    op.create_table('registration_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=10), nullable=False),
    sa.Column('program_code', sa.String(length=10), nullable=False),
    sa.Column('cohort', sa.String(length=10), nullable=False),
    sa.Column('current_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'role_code', 'program_code', 'cohort', name='unique_sequence_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_sequences')
    op.drop_index(op.f('ix_programs_code'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
